

final List<Map<String,String>> hotel = [
  {
    "image":"assets/hotel1.jpg",
    "tittle":"Secrets Akumal Riviera\nMaya",
    "price":"Akumal,Quintana Roo,\nMexico\nFrom£347",
    "ratings":"4.8",
    "review":"(14,347)",
  },
  {
    "image":"assets/hotel2.jpg",
    "tittle":"Grandvrio Ocean\nResort Danang",
    "price":"Dien Ban,Vietnam\nFrom£99",
    "ratings":"4.9",
    "review":"(3,453)",
  },
  {
    "image":"assets/hotel3.jpg",
    "tittle":"Gokulam Grand Turtle\non the Beach",
    "price":"Kovalam,India\nFrom £120",
    "ratings":"5.0",
    "review":"(10,170)",
  },
  {
    "image":"assets/hotel4.jpg",
    "tittle":"Romance Istanbul\nHotel",
    "price":"Istanbul,Turkiye\nFrom £120",
    "ratings":"5.0",
    "review":"(5,999)",
  },
  {
    "image":"assets/hotel5.jpg",
    "tittle":"Bucuti & Tara Beach\nResort Aruba",
    "price":"Palm-Eagle Beach,\nAruba\nFrom £401",
    "ratings":"4.9",
    "review":"(10,413)",
  },
  {
    "image":"assets/hotel6.jpg",
    "tittle":"St.Ermin's Hotel,\nAutograph Collection",
    "price":"London,England\nFrom £341",
    "ratings":"4.9",
    "review":"(8,334)",
  },
  {
    "image":"assets/hotel7.jpg",
    "tittle":"Hyatt Zilara Cap Cana",
    "price":"Cap Cana,Dominican\nRepublic\nFrom £421",
    "ratings":"5.0",
    "review":"(6,828)",
  },
  {
    "image":"assets/hotel8.jpg",
    "tittle":"French Quarter Inn",
    "price":"Charlestaon,US\nFrom £296",
    "ratings":"4.8",
    "review":"(4,057)",
  },
  {
    "image":"assets/hotel9.jpg",
    "tittle":"Chandys Windy\nWoods",
    "price":"Chithirapuram,India\nFrom £145",
    "ratings":"5.0",
    "review":"(8,057)",
  },
  {
    "image":"assets/hotel10.jpg",
    "tittle":"Siyam World Maldives",
    "price":"Dhigurah,Maldives\nFrom £520",
    "ratings":"4.9",
    "review":"(5,057)",
  },
  {
    "image":"assets/hotel11.jpg",
    "tittle":"Hotel Ritta Hoppner",
    "price":"Gramado,State of Rio\nGrande do Sul,Brazil\nFrom £114",
    "ratings":"5.0",
    "review":"(8,057)",
  },
  {
    "image":"assets/hotel12.jpg",
    "tittle":"The Kayon Jungle\nResort",
    "price":"Bresela,Indonesia\nFrom £291",
    "ratings":"5.0",
    "review":"(2,057)",
  },
  {
    "image":"assets/hotel13.jpg",
    "tittle":"Hotel Vision Budapest",
    "price":"Budapest,Hungary\nFrom £123",
    "ratings":"5.0",
    "review":"(1,257)",
  },
  {
    "image":"assets/hotel14.jpg",
    "tittle":"Sani Beach",
    "price":"Sani,Halkidiki Region,\nGreece\nFrom £185",
    "ratings":"5.0",
    "review":"(4,057)",
  },
  {
    "image":"assets/hotel15.jpg",
    "tittle":"Jay House River Park\nHotel",
    "price":"Siem Reap,Cambodia\nFrom £165",
    "ratings":"5.0",
    "review":"(9,057)",
  }, {
    "image":"assets/hotel16.jpg",
    "tittle":"Iberotel Makadi Beach",
    "price":"Makadi Bayy,Egypt\nFrom £185",
    "ratings":"4.8",
    "review":"(3,057)",
  }, {
    "image":"assets/hotel17.jpg",
    "tittle":"Hotel The Cliff Bay",
    "price":"Funchal,Portugal\nFrom £251",
    "ratings":"4.9",
    "review":"(6,057)",
  },
];